[storage]
provider = "local"
# valori: local, google_drive, pcloud

[google_drive]
folder_id = "INSERISCI_ID_CARTELLA_GOOGLE_DRIVE"

[pcloud]
access_token = "INSERISCI_TOKEN_PCLOUD"
folder_id = "0"

[gdrive_service_account]
type = "service_account"
project_id = "INSERISCI_PROJECT_ID"
private_key_id = "INSERISCI_PRIVATE_KEY_ID"
private_key = "INCOLLA_CHIAVE_PRIVATA_GOOGLE"
client_email = "INSERISCI_CLIENT_EMAIL"
client_id = "INSERISCI_CLIENT_ID"
token_uri = "https://oauth2.googleapis.com/token"
